# Generated by Django 5.0.6 on 2024-06-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_description',
        ),
    ]
