# Generated by Django 5.0.6 on 2024-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0002_remove_category_cat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
